sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_search:
    type: portal
    resource: "@SuluSearchBundle/Resources/config/routing_website.yml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"

sulu_admin.logout:
    path: /logout

when@dev:
    _portal_errors:
        resource: "@SuluWebsiteBundle/Resources/config/routing_error.yml"
        type: portal